/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.forms.fInsert;

import uts.*;
import java.util.Random;

/**
 *
 * @author
 */
public class fPesan extends javax.swing.JFrame {

    /**
     * Creates new form fPesan
     */
    ListUnbooked unbookedList;
    ListBooked bookedList;
    int type;

    static String getAlphaNumericString(int n) {

        // chose a Character random from this String
        String AlphaNumericString = "0123456789";

        // create StringBuffer size of AlphaNumericString
        StringBuilder sb = new StringBuilder(n);

        for (int i = 0; i < n; i++) {

            // generate a random number between
            // 0 to AlphaNumericString variable length
            int index
                    = (int) (AlphaNumericString.length()
                    * Math.random());

            // add Character one by one in end of sb
            sb.append(AlphaNumericString
                    .charAt(index));
        }

        return sb.toString();
    }

    public fPesan(ListUnbooked unbookedList, ListBooked bookedList, int type) {
        this.unbookedList = unbookedList;
        this.bookedList = bookedList;
        this.type = type;
        //cuma nambahin comment
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbJadwal = new javax.swing.JComboBox<>();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cbKursi = new javax.swing.JComboBox<>();
        imgEkonomi = new javax.swing.JLabel();
        imgBisnis1 = new javax.swing.JLabel();
        imgFirstClass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cSure = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "9.00", "12.00", "15.00" }));
        cbJadwal.setName("cbJadwal"); // NOI18N
        cbJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJadwalActionPerformed(evt);
            }
        });

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Ekonomi", "Bisnis", "First Class" }));
        cbKelas.setName("cbKelas"); // NOI18N
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });

        jLabel1.setText("Waktu Penerbangan");

        jLabel2.setText("Kelas Penerbangan");

        jLabel3.setText("Kursi Kosong");

        tbNama.setName("tbNama"); // NOI18N

        jButton1.setText("Pesan");
        jButton1.setName("bPesan"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        cbKursi.setName("cbKursi"); // NOI18N
        cbKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKursiActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(cbKursi);

        imgEkonomi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/business-seating1.png"))); // NOI18N

        imgBisnis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/economy-seating1.png"))); // NOI18N
        imgBisnis1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        imgFirstClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/firstclass-seating1.png"))); // NOI18N

        jLabel5.setText("EKONOMI");

        jLabel6.setText("BISNIS");

        jLabel7.setText("FIRST CLASS");

        jLabel8.setText("<- TAIL");

        jLabel9.setText("HEAD ->");

        cSure.setText("Saya menyatakan, data yang saya isikan sudah benar.");
        cSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imgEkonomi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgBisnis1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgFirstClass))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)
                                    .addComponent(tbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(cbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cSure)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgEkonomi)
                    .addComponent(imgBisnis1)
                    .addComponent(imgFirstClass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cSure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cbKelas.getSelectedIndex() == 0 || cbJadwal.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Mohon Pilih Jadwal dan Kursi Terlebih Dahulu!");
        } else if (!cSure.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Mohon centang pada pernyataan data!");
        } else {
            String id = null;
            if (cbKelas.getSelectedItem() == "Ekonomi") {
                id = "EK";
            } else if (cbKelas.getSelectedItem() == "Bisnis") {
                id = "BI";
            } else if (cbKelas.getSelectedItem() == "First Class") {
                id = "FC";
            }
            if (bookedList.first == null) {
                id = id + getAlphaNumericString(4);
            } else {
                boolean valid = false;
                String idTemp;
                do {
                    ElementBooked pointer = bookedList.first;
                    idTemp = id + getAlphaNumericString(4);
                    while (pointer != null) {
                        if (pointer.data.id.equals(idTemp)) {
                            //cbKursi.addItem(pointer.data.kursi);
                            valid = true;
                            id = idTemp;
                            break;
                        }
                        if (pointer.next == null && !(pointer.data.id.equals(idTemp))) {
                            valid = false;
                            break;
                        }
                        pointer = pointer.next;
                    }
                } while (valid);
                id = idTemp;
            }
            switch (type) {
                case 1:
                    bookedList.insertFirst(id, tbNama.getText(), (String) cbJadwal.getSelectedItem(),
                            (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());
                    unbookedList.insertAt(id, tbNama.getText(), (String) cbJadwal.getSelectedItem(),
                            (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());
                    javax.swing.JOptionPane.showMessageDialog(null, "Tiket Berhasil Dipesan dengan ID : " + id);
                    tbNama.setText("");
                    cbJadwal.setSelectedIndex(0);
                    cbKelas.setSelectedIndex(0);
                    cSure.setSelected(false);
                    break;
                case 2:
                    fPesanAt f = new fPesanAt(tbNama, cbJadwal, cbKelas, cbKursi, cSure, unbookedList, bookedList);
                    f.setVisible(true);
                    break;
                default:
                    bookedList.insertLast(id, tbNama.getText(), (String) cbJadwal.getSelectedItem(),
                        (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());
                    unbookedList.insertAt(id, tbNama.getText(), (String) cbJadwal.getSelectedItem(),
                        (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());
                    javax.swing.JOptionPane.showMessageDialog(null, "Tiket Berhasil Dipesan dengan ID : " + id);
                    tbNama.setText("");
                    cbJadwal.setSelectedIndex(0);
                    cbKelas.setSelectedIndex(0);
                    cSure.setSelected(false);
                    break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJadwalActionPerformed

        cbKursi.removeAllItems();
        ElementUnbooked pointer;
        pointer = unbookedList.first;
        for (int i = 1; i <= 36; i++) {
            if (unbookedList.first == null) {
                System.out.println("NANTI");
            } else {
                while (pointer != null) {
                    if (pointer.data.id.equals("") && pointer.data.nama.equals("") && pointer.data.kelas.equals(cbKelas.getSelectedItem())
                            && pointer.data.jadwal.equals(cbJadwal.getSelectedItem())) {
                        cbKursi.addItem(pointer.data.kursi);
                    }
                    pointer = pointer.next;
                }
                break;
            }
        }
    }//GEN-LAST:event_cbJadwalActionPerformed

    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        cbKursi.removeAllItems();
        ElementUnbooked pointer;
        pointer = unbookedList.first;
        for (int i = 1; i <= 36; i++) {
            if (unbookedList.first == null) {
                System.out.println("NANTI");
            } else {
                while (pointer != null) {
                    if (pointer.data.id.equals("") && pointer.data.nama.equals("") && pointer.data.kelas.equals(cbKelas.getSelectedItem())
                            && pointer.data.jadwal.equals(cbJadwal.getSelectedItem())) {
                        cbKursi.addItem(pointer.data.kursi);
                    }
                    pointer = pointer.next;
                }
                break;
            }
        }
    }//GEN-LAST:event_cbKelasActionPerformed

    private void cbKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKursiActionPerformed

    private void cSureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSureActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cSure;
    private javax.swing.JComboBox<String> cbJadwal;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> cbKursi;
    private javax.swing.JLabel imgBisnis1;
    private javax.swing.JLabel imgEkonomi;
    private javax.swing.JLabel imgFirstClass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbNama;
    // End of variables declaration//GEN-END:variables
}
