/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.forms.fInsert;

import uts.*;
import java.util.Random;

/**
 *
 * @author
 */
public class fPesan extends javax.swing.JFrame {

    /**
     * Creates new form fPesan
     */
    ListUnbooked unbookedList;
    ListBooked bookedList;
    int type;

    static String getAlphaNumericString(int n) {

        // chose a Character random from this String
        String AlphaNumericString = "0123456789";

        // create StringBuffer size of AlphaNumericString
        StringBuilder sb = new StringBuilder(n);

        for (int i = 0; i < n; i++) {

            // generate a random number between
            // 0 to AlphaNumericString variable length
            int index
                    = (int) (AlphaNumericString.length()
                    * Math.random());

            // add Character one by one in end of sb
            sb.append(AlphaNumericString
                    .charAt(index));
        }

        return sb.toString();
    }

    public fPesan(ListUnbooked unbookedList, ListBooked bookedList, int type) {
        this.unbookedList = unbookedList;
        this.bookedList = bookedList;
        this.type = type;
        //cuma nambahin comment
        initComponents();
//        cbKelas.addItem("Ekonomi");
//        cbKelas.addItem("Bisnis");
//        cbKelas.addItem("First Class");
//        cbJadwal.addItem("09.00");
//        cbJadwal.addItem("12.00");
//        cbJadwal.addItem("15.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbJadwal = new javax.swing.JComboBox<>();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cbKursi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "9.00", "12.00", "15.00" }));
        cbJadwal.setName("cbJadwal"); // NOI18N
        cbJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJadwalActionPerformed(evt);
            }
        });

        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Ekonomi", "Bisnis", "First Class" }));
        cbKelas.setName("cbKelas"); // NOI18N
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });

        jLabel1.setText("Waktu Penerbangan");

        jLabel2.setText("Kelas Penerbangan");

        jLabel3.setText("Kursi Kosong");

        tbNama.setName("tbNama"); // NOI18N

        jButton1.setText("Pesan");
        jButton1.setName("bPesan"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        cbKursi.setName("cbKursi"); // NOI18N
        cbKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKursiActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(cbKursi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbJadwal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(cbKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(tbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = null;
        if (cbKelas.getSelectedItem() == "Ekonomi") {
            id = "EK";
        } else if (cbKelas.getSelectedItem() == "Bisnis") {
            id = "BI";
        } else if (cbKelas.getSelectedItem() == "First Class") {
            id = "FC";
        }
        if (bookedList.first != null) {
            boolean valid = false;
            String idTemp;
             do{
                ElementBooked pointer = bookedList.first;
                idTemp = id + getAlphaNumericString(4);
                while (pointer != null) {
                    if (pointer.data.id.equals(idTemp)) {
                        //cbKursi.addItem(pointer.data.kursi);
                        valid = true;
                        id = idTemp;
                        break;
                    }
                    if(pointer.next == null && !(pointer.data.id.equals(idTemp))){
                        valid = false;
                        break;
                    }
                    pointer = pointer.next;
                }
            }while (valid);
             id = idTemp;
        } else {
            id = id + getAlphaNumericString(4);
        }
        if (type == 1) {
            bookedList.insertFirst(id, tbNama.getText(), (String) cbJadwal.getSelectedItem(),
                    (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());

            unbookedList.insertAt(id, tbNama.getText(), (String) cbJadwal.getSelectedItem()
                    , (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());
            javax.swing.JOptionPane.showMessageDialog(null, "Tiker Berhasil Dipesan");
            tbNama.setText("");
            cbJadwal.setSelectedIndex(0);
            cbKelas.setSelectedIndex(0);
        } else if (type == 2) {                                           
            fPesanAt f = new fPesanAt(tbNama, cbJadwal, cbKelas, cbKursi, unbookedList, bookedList);
            f.setVisible(true);
        }
        else {
            bookedList.insertLast(id, tbNama.getText(), (String) cbJadwal.getSelectedItem(),
                    (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());

            unbookedList.insertAt(id, tbNama.getText(), (String) cbJadwal.getSelectedItem()
                    , (String) cbKursi.getSelectedItem(), (String) cbKelas.getSelectedItem());
            javax.swing.JOptionPane.showMessageDialog(null, "Tiker Berhasil Dipesan");
            tbNama.setText("");
            cbJadwal.setSelectedIndex(0);
            cbKelas.setSelectedIndex(0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJadwalActionPerformed

        cbKursi.removeAllItems();
        ElementUnbooked pointer;
        pointer = unbookedList.first;
        for (int i = 1; i <= 36; i++) {
            if (unbookedList.first == null) {
                System.out.println("NANTI");
            } else {
                while (pointer != null) {
                    if (pointer.data.id.equals("") && pointer.data.nama.equals("") && pointer.data.kelas.equals(cbKelas.getSelectedItem())
                            && pointer.data.jadwal.equals(cbJadwal.getSelectedItem())) {
                        cbKursi.addItem(pointer.data.kursi);
                    }
                    pointer = pointer.next;
                }
                break;
            }
        }
    }//GEN-LAST:event_cbJadwalActionPerformed

    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        cbKursi.removeAllItems();
        ElementUnbooked pointer;
        pointer = unbookedList.first;
        for (int i = 1; i <= 36; i++) {
            if (unbookedList.first == null) {
                System.out.println("NANTI");
            } else {
                while (pointer != null) {
                    if (pointer.data.id.equals("") && pointer.data.nama.equals("") && pointer.data.kelas.equals(cbKelas.getSelectedItem())
                            && pointer.data.jadwal.equals(cbJadwal.getSelectedItem())) {
                        cbKursi.addItem(pointer.data.kursi);
                    }
                    pointer = pointer.next;
                }
                break;
            }
        }
    }//GEN-LAST:event_cbKelasActionPerformed

    private void cbKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKursiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJadwal;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> cbKursi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbNama;
    // End of variables declaration//GEN-END:variables
}
